In [18]:
import numpy as np

X = np.array([
    [1,1],
    [2,3],
    [3,4],
    [-0.5,-0.5],
    [-1,-2],
    [-2,-3],
    [-3,-4],
    [-4,-3],

])

y = np.array([1,1,1,-1,-1,-1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    eta = 1
    epochs = 2222

    for t in range(epochs):
        for i, x in enumerate(X):
            if (np.dot(X[i], w)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]

    return w

w = perceptron_sgd(X,y)
print(w)

[1. 1.]


In [14]:
X = np.array([
    [1,1],
    [2,3],
    [3,4],
    [-0.5,-0.5],
    [-1,-2],
    [-2,-3],
    [-3,-4],
    [-4,-3],

])

y = np.array([1,1,1,-1,-1,-1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    w0=0
    eta = 1
    epochs = 50

    for t in range(epochs):
        for i, x in enumerate(X):
            if ((np.dot(X[i], w)+w0)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]
                w0= w0+Y[i]

    return w,w0

w = perceptron_sgd(X,y)
print(w)

(array([1.5, 1.5]), 0)


In [20]:
X = np.array([
    [1,1],
    [2,3],
    [3,4],
    [-0.5,-0.5],
    [-1,-2],
    [-2,-3],
    [-3,-4],
    [-4,-3],

])

y = np.array([1,1,1,-1,-1,-1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    w0=0
    eta = 1
    epochs = 50
    count=0

    for t in range(epochs):
        for i, x in enumerate(X):
            if ((np.dot(X[i], w)+w0)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]
                w0= w0+Y[i]
                count=count +1

    return w,w0,count

w = perceptron_sgd(X,y)
print(w)

(array([1.5, 1.5]), 0, 2)


In [34]:
X = np.array([
    [1,1],
    [2,3],
    [3,4],
    [-0.5,-0.5],
    [-1,-2],
    [-2,-3],
    [-3,-4],
    [-4,-3],

])

y = np.array([1,1,1,-1,-1,-1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    w0=0
    eta = 1
    epochs = 1
    count=0

    for t in range(epochs):
        for i, x in enumerate(X):
            if ((np.dot(X[i], w)+w0)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]
#                 w0= w0+Y[i]
                count=count +1
# count son los mistakes
    return w,w0,count

w = perceptron_sgd(X,y)
print(w)

(array([1., 1.]), 0, 1)


In [42]:
.5*2-((3**.5)/2)*2




-0.7320508075688772

In [43]:
(3**.5)/2*3+.5/3

2.7647428780199825

In [61]:
r = np.array([
    [.5,-(3**.5)/2],
    [(3**.5)/2,.5],
])

a = np.array([1,1])
b = np.array([2,3])
c = np.array([3,4])
d = np.array([-0.5,-0.5])
e = np.array([-1,-2])
f = np.array([-2,-3])
g = np.array([-3,-4])
h = np.array([-4,-3])

a=np.dot(r, a)
b=np.dot(r, b)
c=np.dot(r, c)
d=np.dot(r, d)
e=np.dot(r, e)
f=np.dot(r, f)
g=np.dot(r, g)
h=np.dot(r, h)

np.set_printoptions(50)

print(a,b,c,d,e,f,g,h)






[-0.3660254037844386  1.3660254037844386] [-1.598076211353316  3.232050807568877] [-1.9641016151377544  4.598076211353316 ] [ 0.1830127018922193 -0.6830127018922193] [ 1.2320508075688772 -1.8660254037844386] [ 1.598076211353316 -3.232050807568877] [ 1.9641016151377544 -4.598076211353316 ] [ 0.598076211353316 -4.964101615137754]


In [67]:
r = np.array([
    [.5,-(3**.5)/2],
    [(3**.5)/2,.5],
])

a = np.array([1.5,1.5])

np.dot(r, a)



array([-0.549038105676658,  2.049038105676658])

In [66]:
# problema 1.3
X = np.array([
    [-0.3660254037844386 , 1.3660254037844386],
    [-1.598076211353316 , 3.232050807568877],
    [-1.9641016151377544 , 4.598076211353316 ],
    [ 0.1830127018922193 ,-0.6830127018922193],
    [1.2320508075688772 ,-1.8660254037844386 ],
    [1.598076211353316, -3.232050807568877],
    [1.9641016151377544 ,-4.598076211353316],
    [0.598076211353316 ,-4.964101615137754],

])

y = np.array([1,1,1,-1,-1,-1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    w0=0
    eta = 1
    epochs = 1000
    count=0

    for t in range(epochs):
        for i, x in enumerate(X):
            if ((np.dot(X[i], w)+w0)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]
                w0= w0+Y[i]
                count=count +1
# count son los mistakes
    return w,w0,count

w = perceptron_sgd(X,y)
print(w)

(array([-0.5490381056766579,  2.049038105676658 ]), 0, 2)


ValueError: X.shape[0] should be equal to X.shape[1]

In [84]:
s0 = np.array([
    [0,0],
    ])


wss = np.array([
    [-1,0],
    [0,1],
])

wsx = np.array([
    [1,0],
    [0,1],
])

a = np.array([
    [1,0],
    ])

b = np.array([
    [0,1],
    ])

def relu(x):
    return np.maximum(0, x)

In [94]:
# Para AA
st_1 = relu(np.dot(wss,s0.T)+np.dot(wsx,a.T))
st= relu(np.dot(wss,st_1)+np.dot(wsx,a.T))
st


array([[0],
       [0]])

In [97]:
# Para ABB
st_1 = relu(np.dot(wss,s0.T)+np.dot(wsx,a.T))
st= relu(np.dot(wss,st_1)+np.dot(wsx,b.T))
st_f= relu(np.dot(wss,st)+np.dot(wsx,b.T))
st_f

array([[0],
       [2]])

In [98]:
# Para BBA
st_1 = relu(np.dot(wss,s0.T)+np.dot(wsx,b.T))
st= relu(np.dot(wss,st_1)+np.dot(wsx,b.T))
st_f= relu(np.dot(wss,st)+np.dot(wsx,a.T))
st_f

array([[1],
       [2]])