In [1]:
import numpy as np

# Compute Hinge Loss


In [126]:

# y1 = 2
# y2 = 2.7
# y3 = -.7
# y4 = 2
# x1 = np.array([1, 0, 1])
# x2 = np.array([1, 1, 1])
# x3 = np.array([1, 1, -1])
# x4 = np.array([-1, 1, 1])
# w = np.array([0, 1, 2])
# wt = np.transpose(w)

In [55]:
x= np.matrix([[1, 0, 1],
               [1, 1, 1],
               [1, 1, -1],
               [-1, 1, 1]
              ])
y = np.array([2, 2.7, -.7,2]) 
w = np.array([0, 1, 2])

In [31]:
def empirical_risk_hinge_loss_single_step(feature_vector,label,current_theta):
    X=feature_vector
    Y=label
    w=current_theta
    
    if (Y-np.dot(w,X)) >= 1:
        L = 0
    else:
        L = 1- (Y-np.dot(w,X))
    return (L)


In [124]:
def empirical_risk_hinge_loss(feature_matrix, labels, current_theta):

    X=feature_matrix
    Y=labels
    w=current_theta
    sum=0
    T=X.shape[0]
#     wL=[]
    for i in range(T):
        L=empirical_risk_hinge_loss_single_step(np.transpose(X[i]), Y[i], w)
        sum=L+sum
#         wL=np.wL.append(L)
    return (sum/T)

In [125]:
empirical_risk_hinge_loss(x, y, w)

matrix([[1.25]])

# Compute Squared Error Loss


In [ ]:
def empirical_risk_hinge_loss_single_step_squared(feature_vector,label,current_theta):
    X=feature_vector
    Y=label
    w=current_theta
    
    if (Y-np.dot(w,X)) >= 1:
        L = 0
    else:
        L = 1- (Y-np.dot(w,X))
    return (L)

In [202]:
x= np.matrix([[1, 0, 1],
               [1, 1, 1],
               [1, 1, -1],
               [-1, 1, 1]
              ])
y = np.array([2, 2.7, -.7,2]) 
w = np.array([0, 1, 2])

In [226]:
def empirical_risk_hinge_loss_squared(feature_matrix, labels, current_theta):

    X=feature_matrix
    Y=labels
    w=current_theta
    sum=0
    T=X.shape[0]

    for i in range(T):
#         L=(Y[i]-np.dot(w,np.transpose(X[i])))
        L=(Y[i]-np.dot(w,np.transpose(X[i])))*(Y[i]-np.dot(w,np.transpose(X[i])))/2

        sum = L + sum
#         wL=np.wL.append(L)
    return (sum/T)


In [227]:
empirical_risk_hinge_loss_squared(x,y,w)

matrix([[0.1475]])

In [ ]:
def perceptron(feature_matrix, labels, T):

    
    # Your code here
    X=feature_matrix
    Y=labels
    w = np.zeros(len(X[0]))
    w0 = 0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
             w,w0=perceptron_single_step_update(X[i,:], Y[i], w, w0)
    return (w,w0)

In [ ]:
def average_perceptron(feature_matrix, labels, T):

    
    update=(np.zeros(feature_matrix.shape[1]),0) 
    theta_sum=np.array(update[0])
    theta_0_sum=update[1]
    count=0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            update=perceptron_single_step_update(feature_matrix[i],labels[i],update[0],update[1])
            theta_sum=theta_sum+np.array(update[0])
            theta_0_sum=theta_0_sum+update[1]
            count=count+1
            
    avg_theta=theta_sum/count
    avg_theta_0=theta_0_sum/count
    
    return (avg_theta,avg_theta_0)

In [33]:
empirical_risk_hinge_loss_single_step(x2,y2,w)

1.2999999999999998

In [34]:
empirical_risk_hinge_loss_single_step(x1,y1,w)

1

In [35]:
empirical_risk_hinge_loss_single_step(x3,y3,w)

0.7

In [36]:
empirical_risk_hinge_loss_single_step(x4,y4,w)

2

array([ 2. ,  2.7, -0.7,  2. ])