In [1]:
import numpy as np

In [2]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    X=feature_vector
    Y=label
    w=current_theta
    w0=current_theta_0

    if (np.dot(X, w)+w0)*Y <= 0:
        w = w + X*Y
        w0 = w0 + Y              
    return (w,w0)



def perceptron(feature_matrix, labels, T):

    
    # Your code here
    X=feature_matrix
    Y=labels
    w = np.zeros(len(X[0]))
    w0 = 0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
             w,w0=perceptron_single_step_update(X[i,:], Y[i], w, w0)
    return (w,w0)

In [3]:
dataset=np.array([[0,0],[2,0],[1,1],[0,2],[3,3],[4,1],[5,2],[1,4],[4,4],[5,5]])

In [4]:
print("The dataset:\n",dataset)
print(" ")
# now transform the dataset using quadratic kernel


The dataset:
 [[0 0]
 [2 0]
 [1 1]
 [0 2]
 [3 3]
 [4 1]
 [5 2]
 [1 4]
 [4 4]
 [5 5]]
 


In [22]:

# define the kernel using lambda function
k=lambda x:np.array([x[0]**2,np.sqrt(2)*x[0]*x[1],x[1]**2])

In [23]:
k

<function __main__.<lambda>(x)>

In [24]:
# transformed data
data_trans=[]
for x in map(k,dataset):
    data_trans.append(x)

In [25]:
# convert data_trans to numpy


data_trans=np.array(data_trans)

In [26]:
data_trans

array([[ 0.        ,  0.        ,  0.        ],
       [ 4.        ,  0.        ,  0.        ],
       [ 1.        ,  1.41421356,  1.        ],
       [ 0.        ,  0.        ,  4.        ],
       [ 9.        , 12.72792206,  9.        ],
       [16.        ,  5.65685425,  1.        ],
       [25.        , 14.14213562,  4.        ],
       [ 1.        ,  5.65685425, 16.        ],
       [16.        , 22.627417  , 16.        ],
       [25.        , 35.35533906, 25.        ]])

In [31]:
# combined ones and data_trans to get the new data
# ones vector got placed as the first column in the transformed dataset

data_trans=np.hstack([np.ones(dataset.shape[0]).reshape(dataset.shape[0],1),data_trans]) # this is done for to calculate the bias term
print("Transformed dataset:\n",data_trans)


Transformed dataset:
 [[ 1.          0.          0.          0.        ]
 [ 1.          4.          0.          0.        ]
 [ 1.          1.          1.41421356  1.        ]
 [ 1.          0.          0.          4.        ]
 [ 1.          9.         12.72792206  9.        ]
 [ 1.         16.          5.65685425  1.        ]
 [ 1.         25.         14.14213562  4.        ]
 [ 1.          1.          5.65685425 16.        ]
 [ 1.         16.         22.627417   16.        ]
 [ 1.         25.         35.35533906 25.        ]]


In [33]:
w=np.zeros(4) # intialize the parameter vector to be zeros
w

array([0., 0., 0., 0.])

In [29]:
# store the mistakes in a list
mistakes=[1,65,11,31,72,30,0,21,4,15]
label=[-1,-1,-1,-1,-1,1,1,1,1,1]

In [35]:
for i in range(dataset.shape[0]):
    
#     # mistakes got multiplied as according to the perceptron algorithm
#     # the weight vector gets updated only if for each example the algorithm makes
#     # mistake
    w=w+mistakes[i]*label[i]*data_trans[i] 
w

array([-220.      ,   42.      ,  -45.254834,   44.      ])

In [36]:
print(" ")
theta0=w[0]
print("Theta0 is given by ",theta0)
print(" ")
theta=w[1:]
print("Theta vector is given by :\n",theta)

 
Theta0 is given by  -220.0
 
Theta vector is given by :
 [ 42.       -45.254834  44.      ]


In [ ]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    X=feature_vector
    Y=label
    w=current_theta
    w0=current_theta_0

    if (np.dot(X, w)+w0)*Y <= 0:
        w = w + X*Y
        w0 = w0 + Y              
    return (w,w0)

def perceptron(feature_matrix, labels, T):

    
    # Your code here
    X=feature_matrix
    Y=labels
    w = np.zeros(len(X[0]))
    w0 = 0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
             w,w0=perceptron_single_step_update(X[i,:], Y[i], w, w0)
    return (w,w0)